# Generated by Django 4.2.1 on 2023-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_member_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='geeks_field',
            new_name='pix',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
