# Generated by Django 4.2.1 on 2023-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pix',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
