# Generated by Django 4.2.1 on 2023-07-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='acc',
            field=models.PositiveIntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default='uba', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.CharField(default='food', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='rout',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='check', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='narrative',
            field=models.CharField(default='Debit/ACH/000000', max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Processing...', max_length=254),
        ),
    ]
