# Generated by Django 4.2.1 on 2023-07-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_transaction_acc_transaction_bank_transaction_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='narrative',
            field=models.CharField(default='Debit/ACH/', max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='Checking Account', max_length=254),
        ),
    ]
