# Generated by Django 4.2.1 on 2023-07-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_alter_transaction_narrative_alter_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.CharField(choices=[('BOA', 'BOA'), ('WellsFargo', 'Wells Fargo'), ('ChaseBank', 'Chase Bank')], max_length=254),
        ),
    ]
