# Generated by Django 4.2.1 on 2023-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_alter_transaction_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='James', max_length=254),
            preserve_default=False,
        ),
    ]
