# Generated by Django 4.2.4 on 2023-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='checkings',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='savings',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
