# Generated by Django 4.2.4 on 2023-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_alter_member_checkings_alter_member_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
