# Generated by Django 4.2.4 on 2023-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accounttype',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='ssn',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Processing', max_length=254),
        ),
    ]
