# Generated by Django 4.2.4 on 2023-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_alter_member_phone_alter_member_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
