# Generated by Django 4.2.4 on 2023-08-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_alter_member_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Changes',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Marketing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='products',
            field=models.BooleanField(null=True),
        ),
    ]
