# Generated by Django 4.2.4 on 2023-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_member_changes_member_marketing_member_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='accounttype',
            field=models.CharField(default='Premium Gold Account', max_length=254, null=True),
        ),
    ]
