# Generated by Django 4.2.4 on 2023-08-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0023_alter_member_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='accounttype',
            field=models.CharField(default='Personal Account', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pix',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounttype', models.CharField(default='Guest Account', max_length=254, null=True)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('DOB', models.DateField(null=True)),
                ('ssn', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('country', models.CharField(max_length=254, null=True)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('idfront', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('Idback', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('debitcard', models.CharField(choices=[('Virtual', 'Virtual Debit Mastercard'), ('Physical', 'Ship a physical Debit Mastercard to the address provided'), ('None', 'None')], max_length=254)),
                ('products', models.BooleanField(null=True)),
                ('Marketing', models.BooleanField(null=True)),
                ('Guest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
