# Generated by Django 4.2.4 on 2023-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0024_member_dob_alter_member_accounttype_alter_member_pix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Marketing',
            new_name='marketing',
        ),
        migrations.AddField(
            model_name='guest',
            name='policy',
            field=models.BooleanField(null=True),
        ),
    ]
