# Generated by Django 4.2.4 on 2023-08-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0025_rename_marketing_guest_marketing_guest_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Idback',
            new_name='idback',
        ),
    ]
