# Generated by Django 4.2.4 on 2023-08-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0026_rename_idback_guest_idback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
