# Generated by Django 4.2.4 on 2023-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0028_idme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='debitcard',
            field=models.CharField(blank=True, choices=[('Virtual', 'Virtual Debit Mastercard'), ('Physical', 'Ship a physical Debit Mastercard to the address provided'), ('None', 'None')], max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='idback',
            field=models.ImageField(upload_to='ID'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='idfront',
            field=models.ImageField(upload_to='ID'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='marketing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='policy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='products',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='pix',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.CharField(max_length=254),
        ),
    ]
