# Generated by Django 4.2.4 on 2023-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0029_bank_alter_guest_dob_alter_guest_debitcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.TextField(max_length=254),
        ),
    ]
