# Generated by Django 4.2.4 on 2023-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0030_alter_bank_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank',
        ),
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default='gtb bank', max_length=30),
            preserve_default=False,
        ),
    ]
