# Generated by Django 4.2.4 on 2023-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0031_remove_bank_bank_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
