# Generated by Django 4.2.4 on 2023-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0032_contact_us_alter_bank_name_alter_transaction_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
