# Generated by Django 4.2.4 on 2023-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0034_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='DOB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Money Sent', max_length=254),
        ),
    ]
