# Generated by Django 4.2.4 on 2023-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0036_guest_city_guest_postcode_guest_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='open', max_length=254, null=True),
        ),
    ]
